intro to tensorflow

In [58]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.19.0


In [59]:
scalar = tf.constant(8,1)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [60]:
#check the number of dimensions
scalar.ndim
vector = tf.constant([10, 10])
vector
#dimension of vector
vector.ndim
#matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [61]:
matrix.ndim

2

In [62]:
#matrix(new)
an_matrix = tf.constant([[10, 1, 4],
                         [3, 6, 30],
                         [20, 40, 12]], dtype=tf.float16)
an_matrix.ndim

2

In [63]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 3, 5]],
                      [[34, 4, 45],
                       [9, 12, 45]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  3,  5]],

       [[34,  4, 45],
        [ 9, 12, 45]]], dtype=int32)>

In [64]:
tensor.ndim

3

Scalar -> magnitude & no direction

Vector -> magnitude & direction

Matrix -> 2D array of number


Tensor -> an n-D array of numbers

In [65]:
#Variable
changeable_tensor = tf.Variable([10, 7]) #mutable
unchangeable_tensor = tf.constant([10, 7]) #immutable
# unchangeable_tensor = unchangeable_tensor[0].assign(19)

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [66]:
#reassigning in changeable tensor
changeable_tensor = changeable_tensor[0].assign(9)
# unchangeable_tensor[0] = (19)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

# Creating random tensors
*Random tensors and tensors of some arbitrary size which contain random number*

In [67]:
# >>>when 2 seeds are set (global & operational), they are used in conjuction by tf to determine the the random sequence
# >>>if global and operational level random seed are same no shuffling is made
tf.random.set_seed(90)# global random seed
rand_1 = tf.random.Generator.from_seed(42)
rand_1 = rand_1.normal(shape=(3,2))
rand_2 = tf.random.Generator.from_seed(12)
rand_2 = rand_2.normal(shape=(3, 2))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# shuffle images in a tensor

In [68]:
not_shuf = tf.constant([[10, 2],
                        [30, 2],
                        [3, 5]])
#shuffling
shuf = tf.random.shuffle(not_shuf, seed=42)
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[30,  2],
       [ 3,  5],
       [10,  2]], dtype=int32)>

# generators from seed
**Uniform dist** => *all elements have equal probability of occuring*

**normal dist** => *Bell shaped(-age dist)*

In [69]:
g = tf.random.Generator.from_seed(42)
g.normal(shape=(2,2)).numpy()

array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)

In [70]:
#from non-deterministic state
nG = tf.random.Generator.from_non_deterministic_state()
nG = nG.normal(shape=(2,3))

In [71]:
tf.random.shuffle(nG)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.93886894, -1.4542311 , -0.00996491],
       [ 1.2777728 , -0.3940984 , -0.39400506]], dtype=float32)>

# other ways to create tensor

In [72]:
tf.zeros([10, 7]) #tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [73]:
#np arrays into tensors
np_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(np_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# getting infomation abt tensors
1. shape -
2. rank - dimensions
3. axis or dimension
4. Size


In [74]:
# rank 4 tensor
rank_4_tensor = tf.zeros([2, 3, 4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [75]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [76]:
rank_4_tensor[0][0].numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [77]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [78]:
#except the final one:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [79]:
py_list = [1, 2, 3, 4]
rank_2_tensor = tf.constant([[2, 3],
                          [4,9]])
rank_2_tensor.shape, rank_2_tensor.ndim, py_list[-1]

(TensorShape([2, 2]), 2, 4)

In [80]:
##last element
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

In [81]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [9]]], dtype=int32)>

In [82]:
tf.expand_dims(rank_2_tensor, axis=-1)# "-1" means expand at the -1 index (final axis)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [9]]], dtype=int32)>

## manipulating tensors( tensors operations)

* *Basic operations*

-, +, /, *


In [83]:
tensor = tf.constant([[7, 3], [2, 5]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 13],
       [12, 15]], dtype=int32)>

In [84]:
#multiplication
tensor * 10

tf.math.multiply(tensor, 10) # or => tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 30],
       [20, 50]], dtype=int32)>

##Matrix multiplication
 resources:=> [mathsisfun.com/algebra](https://www.mathsisfun.com/algebra)

 visualize =>
*[matrixmultiplication.xyz](https://matrixmultiplication.xyz)*

In [85]:
tensor
tf.matmul(tensor, tensor) ## tf.linalg.matmul()
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 36],
       [24, 31]], dtype=int32)>

In [86]:
x = tf.constant([[[]]])

**multiplying matrices**

*must have the similar inner axis*

In [94]:
x = tf.constant([[1, 2, 1],
                 [0, 1,0],
                 [2, 3, 4]])
y = tf.constant([[2, 5],
                 [6, 7],
                 [1, 8]])
x @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

**Dot Product**

* tf.linalg.matmul()

* tf.tensordot()

* **when multiplying two matrix use .transponse instead of reshaping the tensor**

In [90]:
# x, y requires to be transposed
tf.tensordot(tf.transpose(x), y, axes=1) # tf.linalg.tensordot() -> main alias

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 21],
       [13, 41],
       [ 6, 37]], dtype=int32)>

In [106]:
##matrix multiplication btwn x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[18, 17],
       [ 5,  1],
       [43, 49]], dtype=int32)>

In [105]:
tf.matmul(x, tf.reshape(y, (3, 2)))
y
# tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 5, 6],
       [7, 1, 8]], dtype=int32)>

#Changing the dType of tensor

#casting to a diff dtype => precision

In [107]:
a = tf.constant([7, 20])
a.dtype

tf.int32

In [111]:
b = tf.constant([1.1, 0.9])
b.dtype
b = tf.cast(b, dtype= tf.float16)
b.dtype

tf.float16

#aggregating tensors
* condensing them from multiple values down to a smaller amount of values

In [115]:
#getting the absolute value
d = tf.constant([-3, -10])
tf.abs(d).numpy()

array([ 3, 10], dtype=int32)

*forms of aggregation*

minimum, maximum, mean and
sum

In [ ]:
#rand tensor
e = tf.constant(np.random.randint(0, 100, size=50))