#   **INTRODUCTION TO TENSORFLOW**

In [57]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.19.0


In [58]:
scalar = tf.constant(8,1)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [59]:
#check the number of dimensions
scalar.ndim
vector = tf.constant([10, 10])
vector
#dimension of vector
vector.ndim
#matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [60]:
matrix.ndim

2

In [61]:
#matrix(new)
an_matrix = tf.constant([[10, 1, 4],
                         [3, 6, 30],
                         [20, 40, 12]], dtype=tf.float16)
an_matrix.ndim

2

In [62]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 3, 5]],
                      [[34, 4, 45],
                       [9, 12, 45]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  3,  5]],

       [[34,  4, 45],
        [ 9, 12, 45]]], dtype=int32)>

In [63]:
tensor.ndim

3

Scalar -> magnitude & no direction

Vector -> magnitude & direction

Matrix -> 2D array of number


Tensor -> an n-D array of numbers

In [64]:
#Variable
changeable_tensor = tf.Variable([10, 7]) #mutable
unchangeable_tensor = tf.constant([10, 7]) #immutable
# unchangeable_tensor = unchangeable_tensor[0].assign(19)

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [65]:
#reassigning in changeable tensor
changeable_tensor = changeable_tensor[0].assign(9)
# unchangeable_tensor[0] = (19)
changeable_tensor

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

# Creating random tensors
*Random tensors and tensors of some arbitrary size which contain random number*

In [11]:
# >>>when 2 seeds are set (global & operational), they are used in conjuction by tf to determine the the random sequence
# >>>if global and operational level random seed are same no shuffling is made
tf.random.set_seed(90)# global random seed
rand_1 = tf.random.Generator.from_seed(42)
rand_1 = rand_1.normal(shape=(3,2))
rand_2 = tf.random.Generator.from_seed(12)
rand_2 = rand_2.normal(shape=(3, 2))

rand_1, rand_2, rand_1 == rand_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967],
        [ 0.37944323, -0.6664026 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# shuffle images in a tensor

In [12]:
not_shuf = tf.constant([[10, 2],
                        [30, 2],
                        [3, 5]])
#shuffling
shuf = tf.random.shuffle(not_shuf, seed=42)
shuf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[30,  2],
       [ 3,  5],
       [10,  2]], dtype=int32)>

# generators from seed
**Uniform dist** => *all elements have equal probability of occuring*

**normal dist** => *Bell shaped(-age dist)*

In [13]:
g = tf.random.Generator.from_seed(42)
g.normal(shape=(2,2)).numpy()

array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)

In [14]:
#from non-deterministic state
nG = tf.random.Generator.from_non_deterministic_state()
nG = nG.normal(shape=(2,3))

In [15]:
tf.random.shuffle(nG)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.4341402 , -1.6360029 , -0.26373422],
       [-1.257975  , -0.06457072,  1.1989894 ]], dtype=float32)>

# other ways to create tensor

In [16]:
tf.zeros([10, 7]) #tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
#np arrays into tensors
np_A = np.arange(1, 25, dtype=np.int32)
A = tf.constant(np_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# getting infomation abt tensors
1. shape -
2. rank - dimensions
3. axis or dimension
4. Size


In [18]:
# rank 4 tensor
rank_4_tensor = tf.zeros([2, 3, 4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [20]:
rank_4_tensor[0][0].numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [21]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
#except the final one:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
py_list = [1, 2, 3, 4]
rank_2_tensor = tf.constant([[2, 3],
                          [4,9]])
rank_2_tensor.shape, rank_2_tensor.ndim, py_list[-1]

(TensorShape([2, 2]), 2, 4)

In [24]:
##last element
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 9], dtype=int32)>

In [25]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [9]]], dtype=int32)>

In [26]:
tf.expand_dims(rank_2_tensor, axis=-1)# "-1" means expand at the -1 index (final axis)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [9]]], dtype=int32)>

## manipulating tensors( tensors operations)

* *Basic operations*

-, +, /, *


In [27]:
tensor = tf.constant([[7, 3], [2, 5]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 13],
       [12, 15]], dtype=int32)>

In [28]:
#multiplication
tensor * 10

tf.math.multiply(tensor, 10) # or => tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[70, 30],
       [20, 50]], dtype=int32)>

##Matrix multiplication
 resources:=> [mathsisfun.com/algebra](https://www.mathsisfun.com/algebra)

 visualize =>
*[matrixmultiplication.xyz](https://matrixmultiplication.xyz)*

In [29]:
tensor
tf.matmul(tensor, tensor) ## tf.linalg.matmul()
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 36],
       [24, 31]], dtype=int32)>

In [30]:
x = tf.constant([[[]]])

**multiplying matrices**

*must have the similar inner axis*

In [31]:
x = tf.constant([[1, 2, 1],
                 [0, 1,0],
                 [2, 3, 4]])
y = tf.constant([[2, 5],
                 [6, 7],
                 [1, 8]])
x @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

**Dot Product**

* tf.linalg.matmul()

* tf.tensordot()

* **when multiplying two matrix use .transponse instead of reshaping the tensor**

In [32]:
# x, y requires to be transposed
tf.tensordot(tf.transpose(x), y, axes=1) # tf.linalg.tensordot() -> main alias

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 21],
       [13, 41],
       [ 6, 37]], dtype=int32)>

In [33]:
##matrix multiplication btwn x and y (transposed)
tf.matmul(x, y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [34]:
tf.matmul(x, tf.reshape(y, (3, 2)))
y
# tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

#Changing the dType of tensor

#casting to a diff dtype => precision

In [35]:
a = tf.constant([7, 20])
a.dtype

tf.int32

In [36]:
b = tf.constant([1.1, 0.9])
b.dtype
b = tf.cast(b, dtype= tf.float16)
b.dtype

tf.float16

#aggregating tensors
* condensing them from multiple values down to a smaller amount of values

In [37]:
#getting the absolute value
d = tf.constant([-3, -10])
tf.abs(d).numpy()

array([ 3, 10], dtype=int32)

*forms of aggregation*

minimum, maximum, mean and
sum

In [38]:
#rand tensor
e = tf.constant(np.random.randint(1, 101, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 80,  88,  84,  54,  37,  67,  53,  67,  18,  46,  66,  55,  87,
        42,  84,   3,  41,   4,   5,  62,  26,  75,   8,  76,  21,  55,
        31,  15,  32,  97,  90,   5,  42, 100,  69,  69,  81,   2,  44,
        71,   1,   4,  88,  78,  48,  30,  92,  77,  75,  51])>

In [39]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [40]:
tf.reduce_min(e)


<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [41]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=100>

In [42]:
#mean
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [43]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2596>

**finding Variance and standard deviation of `e`**

In [44]:
variance = tf.math.reduce_variance(tf.cast(e, dtype=tf.float16))
variance

<tf.Tensor: shape=(), dtype=float16, numpy=882.5>

In [45]:

std = tf.math.reduce_std(tf.cast(e, dtype=tf.float16))
std
# e

<tf.Tensor: shape=(), dtype=float16, numpy=29.703125>

# Positional maximum and minimum
* in which maximum and/or minimum occurs

In [46]:
tf.random.set_seed(40)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
       0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
       0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
       0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
       0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
       0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
       0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
       0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
       0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
       0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553],
      dtype=float32)>

In [47]:
## return the largest value across axes of a tensor
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [48]:
#index on the largest value
ne = f[tf.argmax(f)]

In [49]:
#using max method
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952852725982666>

In [50]:
assert tf.reduce_max(f) == f[tf.argmax(f)]

In [51]:
#positional minimum
tf.argmin(f)
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.03102552890777588>

In [52]:
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.03102552890777588>

In [53]:
assert tf.reduce_min(f) == f[tf.argmin(f)]

# squeezing a Tensor

In [54]:
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.74675906, 0.24612856, 0.52820086, 0.8276756 , 0.6183318 ,
           0.0846777 , 0.13903832, 0.04563856, 0.6154578 , 0.44305432,
           0.7431537 , 0.9795221 , 0.54386437, 0.21016955, 0.24788725,
           0.35024524, 0.03533351, 0.65845823, 0.24004912, 0.1725409 ,
           0.22278512, 0.2606182 , 0.37575412, 0.9490981 , 0.3538996 ,
           0.4968046 , 0.18215156, 0.87830687, 0.08035612, 0.9584689 ,
           0.11927223, 0.48161948, 0.46814215, 0.26376808, 0.33337045,
           0.9157454 , 0.8242643 , 0.00191033, 0.2706449 , 0.75256467,
           0.07479346, 0.25697482, 0.10337758, 0.5379051 , 0.2707088 ,
           0.02460349, 0.06105328, 0.42337906, 0.30669105, 0.30637336]]]]],
      dtype=float32)>

In [55]:
g_squeezed = tf.squeeze(g) #Removes dimensions of size 1 from the shape of a tenso
g_squeezed.shape

TensorShape([50])

# One hot encoding

In [71]:
depth = 4
fruits = [1, 3, 9, 6]
tf.one_hot(fruits, depth, on_value=5.0, off_value=-1.0) # categorical indices to binary matrrix presentations


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-1.,  5., -1., -1.],
       [-1., -1., -1.,  5.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]], dtype=float32)>

In [78]:
#math ops with one hot encoding
h = tf.range(1, 10)
h = tf.square(h)
tf.math.sqrt(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [83]:
##logging
tf.math.log(tf.cast(h, dtype=tf.float32))
# tf.math.cos(tf.cast(h, dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 1.3862944, 2.1972246, 2.7725887, 3.218876 , 3.583519 ,
       3.8918204, 4.158883 , 4.394449 ], dtype=float32)>

# Tensorflow and Numpy

In [87]:
j = tf.constant(np.array([2., 5., 12.]))
j.dtype, np.array(j), type(np.array(j)) #or j.arrray(), type(j.numpy())

## on creating tensor using numpy the default ddtype is float64 unlike in tf
## where it's float32

(tf.float64, array([ 2.,  5., 12.]), numpy.ndarray)

##Neural Network Regression with Tensorflow


---


*   Architecture of neural network regression model
*  Input shape and output shapes of regression model (features and labels)
* creating custom data to view and fit
* steps in  modelling   
  * Creating, compiling a model, fitting a model, evaluating a model
* Different evaluation methods
* saving and loading models


In [89]:
## autioning a house with 4 bedrooms, 2 cars, 2 bathrooms
### [bedrooms, cars, bathrooms] => shape = [3]
features = tf.constant([4, 2, 2])
encoding_features = tf.one_hot(features, depth=5)
encoding_features

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)>